services:
  nexus:
    image: sonatype/nexus3:3.96.0-alpine
    container_name: zephyrworks-nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped

volumes:
  nexus_data:
