sonar.projectKey=ZephyrWorks-Turbine-API
sonar.projectName=ZephyrWorks Turbine API
sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/__pycache__/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
