apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbine-api
  namespace: zephyrworks
  labels:
    app: turbine-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: turbine-api
  template:
    metadata:
      labels:
        app: turbine-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: turbine-api
          image: zephyrworks-turbine-api:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          volumeMounts:
            - name: gunicorn-control
              mountPath: /home/app/.gunicorn
            - name: temporary-files
              mountPath: /tmp
      volumes:
        - name: gunicorn-control
          emptyDir: {}
        - name: temporary-files
          emptyDir:
            sizeLimit: 16Mi
